---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: db
  clusterIP: None
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mysql:8.0.33
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: demo
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: pass

          resources:
            limits:
              memory: "512Mi"
              cpu: "300m"
          ports:
            - containerPort: 3306