apiVersion: v1
kind: Service
metadata:
  name: monolithic-svc
spec:
  selector:
    app: pdf-creator
    type: backend
    name: monolithic
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolithic
spec:
  selector:
    matchLabels:
      app: pdf-creator
      type: backend
      name: monolithic
  template:
    metadata:
      labels:
        app: pdf-creator
        type: backend
        name: monolithic
    spec:
      containers:
        - name: monolithic
          image: monolithic:1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
