apiVersion: v1
kind: Service
metadata:
  name: pdf-svc
spec:
  selector:
    app: pdf-creator
    type: backend
    name: pdf
  ports:
    - port: 80
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf
spec:
  selector:
    matchLabels:
      app: pdf-creator
      type: backend
      name: pdf
  template:
    metadata:
      labels:
        app: pdf-creator
        type: backend
        name: pdf
    spec:
      containers:
        - name: pdf
          image: pdf:1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
