version: '3.7'
services:
  db:
    image: mysql:8.0.33
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"

    volumes:
      - my-datavolume:/var/lib/mysql
  nats:
    image: nats:alpine
    ports:
      - "4222:4222"
      - "8222:8222"
volumes:
  my-datavolume:
